title: Luca De Gennaro Aquino
description: 12 Rue Pierre Semard, 38000 Grenoble, France  
             <p> Grenoble Ecole de Management, Office F813b  
             <p> luca.degennaroaquino@grenoble-em.com  
theme: jekyll-theme-cayman
google_analytics: UA-151887795-1
