title: Luca De Gennaro Aquino
description: Grenoble Ecole de Management   
             <p> 12 Rue Pierre Semard, 38000 Grenoble, France  
             <p> Office F813b  
             <p> luca.degennaroaquino@grenoble-em.com  
google_analytics: UA-151887795-1
