title: Luca De Gennaro Aquino
description: 12 Rue Pierre Semard  
             <p> Grenoble Ecole de Management  <\p>
             <p> 38000 Grenoble, France  <\p>
             
             <p> Office F813b  <\p>
             
             <p> luca.degennaroaquino@grenoble-em.com  <\p>
             
             <p> ORCID https://orcid.org/0000-0001-5377-5385  <\p>
theme: jekyll-theme-cayman
google_analytics: UA-151887795-1
