title: Luca De Gennaro Aquino
description: 12 Rue Pierre Semard

Grenoble Ecole de Management

38000 Grenoble, France

Office F813b

<luca.degennaroaquino@grenoble-em.com>

ORCID <https://orcid.org/0000-0001-5377-5385>

theme: jekyll-theme-cayman
google_analytics: UA-151887795-1
